<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Hash;

class PayslipResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
       
        return [
            'id' => $this->id,
            'employee_id' => $this->employee_id,
            'periode' => $this->periode,
            'gaji_pokok' => $this->gaji_pokok,
            'tunj_posisi_struktural' => $this->tunj_posisi_struktural,
            'gaji_komisaris' => $this->gaji_komisaris,
            'insentif_lalin' => $this->insentif_lalin,
            'uang_pengganti' => $this->uang_pengganti,
            'kompensasi_ap' => $this->kompensasi_ap,
            'tunjangan_perumahan_dir_' => $this->tunjangan_perumahan_dir_,
            'tunjangan_transport_kom_' => $this->tunjangan_transport_kom_,
            'tunjangan_telekomunikasi' => $this->tunjangan_telekomunikasi,
            'insentif' => $this->insentif,
            'kompensasi_penghasilan' => $this->kompensasi_penghasilan,
            'tunj_posisi_ops_grade' => $this->tunj_posisi_ops_grade,
            'tunj_posisi_fungsional' => $this->tunj_posisi_fungsional,
            'gaji_direksi' => $this->gaji_direksi,
            'tunjangan_psl' => $this->tunjangan_psl,
            'gaji_komite' => $this->gaji_komite,
            'lalin_reg_i_masuk' => $this->lalin_reg_i_masuk,
            'lalin_reg_i_keluar' => $this->lalin_reg_i_keluar,
            'lalin_reg_i_terbuka' => $this->lalin_reg_i_terbuka,
            'lalin_reg_multi_masuk' => $this->lalin_reg_multi_masuk,
            'lalin_reg_multi_keluar' => $this->lalin_reg_multi_keluar,
            'lalin_reg_multi_terbuka' => $this->lalin_reg_multi_terbuka,
            'lalin_gto_gol_i_masuk' => $this->lalin_gto_gol_i_masuk,
            'lalin_gto_gol_i_keluar' => $this->lalin_gto_gol_i_keluar,
            'lalin_gto_gol_i_terbuka' => $this->lalin_gto_gol_i_terbuka,
            'lalin_gto_multi_masuk' => $this->lalin_gto_multi_masuk,
            'lalin_gto_multi_keluar' => $this->lalin_gto_multi_keluar,
            'lalin_gto_multi_terbuka' => $this->lalin_gto_multi_terbuka,
            'lalin_jmpt_kndraan_masuk' => $this->lalin_jmpt_kndraan_masuk,
            'lalin_jmpt_trnsksi_trbuka' => $this->lalin_jmpt_trnsksi_trbuka,
            'beban_ruas_a' => $this->beban_ruas_a,
            'beban_ruas_b' => $this->beban_ruas_b,
            'beban_ruas_c' => $this->beban_ruas_c,
            'beban_ruas_d' => $this->beban_ruas_d,
            'beban_ruas_e' => $this->beban_ruas_e,
            'beban_ruas_f' => $this->beban_ruas_f,
            'kompensasi_kgp' => $this->kompensasi_kgp,
            'insentif_ramadhan' => $this->insentif_ramadhan,
            'tunjangan_cuti' => $this->tunjangan_cuti,
            'uang_lembur_150_' => $this->uang_lembur_150_,
            'uang_lembur_200_' => $this->uang_lembur_200_,
            'uang_lembur_300_' => $this->uang_lembur_300_,
            'uang_lembur_400_' => $this->uang_lembur_400_,
            'uang_lembur_fix' => $this->uang_lembur_fix,
            'uang_lembur_150_md' => $this->uang_lembur_150_md,
            'uang_lembur_200_hln' => $this->uang_lembur_200_hln,
            'uang_lembur_200_md' => $this->uang_lembur_200_md,
            'uang_makan' => $this->uang_makan,
            'uang_saku_transport_lokal' => $this->uang_saku_transport_lokal,
            'uang_penginapan_sementara' => $this->uang_penginapan_sementara,
            'bantuan_sewa_rumah' => $this->bantuan_sewa_rumah,
            'tunjangan_angkutan' => $this->tunjangan_angkutan,
            'utb_luar_negeri' => $this->utb_luar_negeri,
            'utb_3_7_jam' => $this->utb_3_7_jam,
            'utb_7' => $this->utb_7,
            'uang_transport_dlm_kota' => $this->uang_transport_dlm_kota,
            'uang_transport_luar_kota' => $this->uang_transport_luar_kota,
            'uang_transport_menginap' => $this->uang_transport_menginap,
            'hotel' => $this->hotel,
            'pesawat' => $this->pesawat,
            'uang_saku_transport_lokal_ln' => $this->uang_saku_transport_lokal_ln,
            'hotel_ln' => $this->hotel_ln,
            'pesawat_ln' => $this->pesawat_ln,
            'tunj_kesehatan_jr' => $this->tunj_kesehatan_jr,
            'tunj_kesehatan_jr_ps_' => $this->tunj_kesehatan_jr_ps_,
            'tunj_kesehatan_ir' => $this->tunj_kesehatan_ir,
            'reimburse_kesehatan_lain' => $this->reimburse_kesehatan_lain,
            'tunj_kesehatan_komisaris' => $this->tunj_kesehatan_komisaris,
            'tunj_kesehatan_direksi' => $this->tunj_kesehatan_direksi,
            'tunj_kesehatan_ir_ps_' => $this->tunj_kesehatan_ir_ps_,
            'jasprod_um_reg' => $this->jasprod_um_reg,
            'thr_regular' => $this->thr_regular,
            'jasprod_final_reg' => $this->jasprod_final_reg,
            'potongan_koperasi' => $this->potongan_koperasi,
            'potongan_iik' => $this->potongan_iik,
            'potongan_skjm' => $this->potongan_skjm,
            'potongan_santunan_duka' => $this->potongan_santunan_duka,
            'potongan_lain_lain' => $this->potongan_lain_lain,
            'pinj_penddkn_sd' => $this->pinj_penddkn_sd,
            'potongan_perjalanan_dinas' => $this->potongan_perjalanan_dinas,
            'potongan_kerohanian' => $this->potongan_kerohanian,
            'potongan_bki' => $this->potongan_bki,
            'potongan_bkk' => $this->potongan_bkk,
            'potongan_bkh' => $this->potongan_bkh,
            'potongan_bkb' => $this->potongan_bkb,
            'potongan_kesehatan_ii' => $this->potongan_kesehatan_ii,
            'potongan_kesehatan_ji' => $this->potongan_kesehatan_ji,
            'dpp_skjm_10' => $this->dpp_skjm_10,
            'dpc_skjm_90' => $this->dpc_skjm_90,
            'pinj_penddkn_smp' => $this->pinj_penddkn_smp,
            'pinj_penddkn_sma' => $this->pinj_penddkn_sma,
            'pinj_penddkn_pt' => $this->pinj_penddkn_pt,
            'pinj_um_rumah' => $this->pinj_um_rumah,
            'pinj_um_kendaraan' => $this->pinj_um_kendaraan,
            'pinj_renovasi_rumah' => $this->pinj_renovasi_rumah,
            'pinj_multiguna' => $this->pinj_multiguna,
            'pinj_kesehatan' => $this->pinj_kesehatan,
            'asuransi_pinjaman' => $this->asuransi_pinjaman,
            'pembayaran_via_fa_cashier' => $this->pembayaran_via_fa_cashier,
            'loan_balance' => $this->loan_balance,
            'phdp' => $this->phdp,
            'phda' => $this->phda,
            'info_pot_kesehatan_jr' => $this->info_pot_kesehatan_jr,
            'gaji_jm_info' => $this->gaji_jm_info,
            'gaji_ap_info' => $this->gaji_ap_info,
            'info_hilang_jam_kerja' => $this->info_hilang_jam_kerja,
            'info_ketidakhadiran' => $this->info_ketidakhadiran,
            'info_kesehatan_ji' => $this->info_kesehatan_ji,
            'info_kesehatan_ii' => $this->info_kesehatan_ii,
            'info_pot_kesehatan_ir' => $this->info_pot_kesehatan_ir,
            'info_hilang_jam_kerja_tp_' => $this->info_hilang_jam_kerja_tp_,
            'info_hilang_jam_kerja_md' => $this->info_hilang_jam_kerja_md,
            'inf_ketidakhadiran_md_' => $this->inf_ketidakhadiran_md_,
            'ee_purna_karya' => $this->ee_purna_karya,
            'ee_dpjm' => $this->ee_dpjm,
            'ee_ppip_jiwasraya' => $this->ee_ppip_jiwasraya,
            'er_purna_karya' => $this->er_purna_karya,
            'er_dpjm' => $this->er_dpjm,
            'er_ppip_jiwasraya' => $this->er_ppip_jiwasraya,
            'bank_transfer' => $this->bank_transfer,
            'ee_jkk' => $this->ee_jkk,
            'ee_jht' => $this->ee_jht,
            'ee_jkm' => $this->ee_jkm,
            'tunj_posisi_ops_job' => $this->tunj_posisi_ops_job,
            'tunjangan_pajak' => $this->tunjangan_pajak,
            'ee_bpjs_hlth_stand_contrb' => $this->ee_bpjs_hlth_stand_contrb,
            'ee_bpjs_heal_add_contrb' => $this->ee_bpjs_heal_add_contrb,
            'ee_bpjs_pens_contrb_' => $this->ee_bpjs_pens_contrb_,
            'er_jkk' => $this->er_jkk,
            'er_jht' => $this->er_jht,
            'er_jkm' => $this->er_jkm,
            'gaji_minus' => $this->gaji_minus,
            'tunjangan_ap_utuh' => $this->tunjangan_ap_utuh,
            'er_bpjs_heal_stand_contrib' => $this->er_bpjs_heal_stand_contrib,
            'er_bpjs_heal_add_contrib' => $this->er_bpjs_heal_add_contrib,
            'er_bpjs_pens_contrib' => $this->er_bpjs_pens_contrib,
            'gaji_pokok_utuh' => $this->gaji_pokok_utuh,
            'total_pph21' => $this->total_pph21,
            'total_gaji_kotor' => $this->total_gaji_kotor,
            'rapel_gaji_pokok' => $this->rapel_gaji_pokok,
            'pengembalian_potongan_pinjaman' => $this->pengembalian_potongan_pinjaman,
            'rapel_tunj_posisi_struktural' => $this->rapel_tunj_posisi_struktural,
            'rapel_tunj_posisi_fungsional' => $this->rapel_tunj_posisi_fungsional,
            'rapel_tunj_posisi_operasional' => $this->rapel_tunj_posisi_operasional,
            'rapel_lembur' => $this->rapel_lembur,
            'pengembalian_pot_kehadiran' => $this->pengembalian_pot_kehadiran,
            'tunj_pos_tambahan' => $this->tunj_pos_tambahan,
            'insert_date' => $this->insert_date,
            'beban_ruas_g' => $this->beban_ruas_g,
            'koreksi_gaji' => $this->koreksi_gaji,
            'pinj_belmera' => $this->pinj_belmera,
            'insentif_lalin_amount' => $this->insentif_lalin_amount,
            'thr_off_cycle' => $this->thr_off_cycle,
            'jasprod_um_off' => $this->jasprod_um_off,
            'jasprod_final' => $this->jasprod_final,
            'potongan_iik_1' => $this->potongan_iik_1,
            'uang_makan_ln' => $this->uang_makan_ln,
            'kompensasi_ap_tambahan' => $this->kompensasi_ap_tambahan,
            'published' => $this->published,
            'ee_purna_karya_askum' => $this->ee_purna_karya_askum,
            'er_purna_karya_askum' => $this->er_purna_karya_askum,
            'cuti_sakit_pengurang_gaji_poko' => $this->cuti_sakit_pengurang_gaji_poko,
            'uang_pengganti_ap' => $this->uang_pengganti_ap,
            'uang_pengganti_ist_panjang' => $this->uang_pengganti_ist_panjang,
            'pay_type' => $this->pay_type,
            'sumbangan_jasprod' => $this->sumbangan_jasprod,
            'pajak' => $this->pajak,
            'potongan_kompensasi' => $this->potongan_kompensasi,
            'tantiem' => $this->tantiem,
            'pajak_umjp_beban_karyawan' => $this->pajak_umjp_beban_karyawan,
            'pot_koperasi_off_cycle' => $this->pot_koperasi_off_cycle,
            'pengembalian_thr' => $this->pengembalian_thr,
            'pajak_insentif_beban_karyawan' => $this->pajak_insentif_beban_karyawan,
            'insentif_satgas' => $this->insentif_satgas,
            'pajak_jp_beban_karyawan' => $this->pajak_jp_beban_karyawan,
            'uang_pengganti_jm' => $this->uang_pengganti_jm,
            'rapel_ee_purna_karya' => $this->rapel_ee_purna_karya,
            'rapel_er_purna_karya' => $this->rapel_er_purna_karya,
            'rapel_ee_askum' => $this->rapel_ee_askum,
            'rapel_er_askum' => $this->rapel_er_askum,
            'er_iuran_pasti' => $this->er_iuran_pasti,
            'ee_iuran_pasti' => $this->ee_iuran_pasti,
            'phdp_tambahan' => $this->phdp_tambahan,
            'bank_trf_control' => $this->bank_trf_control,
            'rapel_ee_iuran_pasti' => $this->rapel_ee_iuran_pasti,
            'rapel_er_iuran_pasti' => $this->rapel_er_iuran_pasti,
            'tunj_posisi_ops_job_x_' => $this->tunj_posisi_ops_job_x_,
            'tunj_posisi_fungsional_x_' => $this->tunj_posisi_fungsional_x_,
            'info_kesehatan_ii_x_' => $this->info_kesehatan_ii_x_,
            'info_kesehatan_ji_x_' => $this->info_kesehatan_ji_x_,
            'potongan_kesehatan_ji_x_' => $this->potongan_kesehatan_ji_x_,
            'potongan_kesehatan_ii_x_' => $this->potongan_kesehatan_ii_x_,
            'reimburse_kesehatan_lain_x_' => $this->reimburse_kesehatan_lain_x_,
            'uang_saku_transport_lokal_ln_x' => $this->uang_saku_transport_lokal_ln_x,
            'uang_saku_transport_lokal_x_' => $this->uang_saku_transport_lokal_x_,
            'uang_makan_x_' => $this->uang_makan_x_,
            'uang_makan_ln_x_' => $this->uang_makan_ln_x_,
            'info_pot_ap_lainnya' => $this->info_pot_ap_lainnya,
            'upah_bpjs_naker_ap' => $this->upah_bpjs_naker_ap,
            'upah_bpjs_naker_induk' => $this->upah_bpjs_naker_induk,
            'ongkos_istirahat_panjang' => $this->ongkos_istirahat_panjang,
            'tunj_multiple_assignment' => $this->tunj_multiple_assignment,
            'payment_external' => $this->payment_external,
            'info_ketidakhadiran_md_' => $this->info_ketidakhadiran_md_,
            'retro' => $this->retro,
            'tunjangan_khusus' => $this->tunjangan_khusus,
            'pinj_mpp' => $this->pinj_mpp,
            'tunjangan_tambahan' => $this->tunjangan_tambahan,
            'type' => $this->type,
            'bank_account' => $this->bank_account,
            'bank_name' => $this->bank_name,
        ];
    }

    public function withResponse($request, $response)
    {
        $jsonResponse = json_decode($response->getContent(), true);
        $response->setContent(json_encode([
            'status' => true,
            'code' => 200,
            'message' => 'Success Detail Data',
            'data' => $jsonResponse
        ]));
    }
}
